"""La till font och profilbild

Revision ID: 22f53d3aa1ac
Revises: a18d1a48349a
Create Date: 2025-05-03 17:17:02.298213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f53d3aa1ac'
down_revision = 'a18d1a48349a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('font_family', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('theme_color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('theme_color')
        batch_op.drop_column('font_family')

    # ### end Alembic commands ###
