"""add email and phone numbr

Revision ID: 32b50a3aa680
Revises: 69ba06a8f5a8
Create Date: 2025-05-13 22:42:52.106564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b50a3aa680'
down_revision = '69ba06a8f5a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('show_email', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('show_phone', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('show_phone')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('show_email')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
