"""Add Stripe billing fields

Revision ID: 5f52078ede10
Revises: 39ba045a29fb
Create Date: 2025-05-30 15:54:56.235834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f52078ede10'
down_revision = '39ba045a29fb'
branch_labels = None
depends_on = None


def upgrade():
    # Get the current database connection
    bind = op.get_bind()

    # 1) Add new columns for Stripe billing
    op.add_column('user', sa.Column('is_premium', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('user', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('stripe_subscription_id', sa.String(), nullable=True))

    # 2) Only run ALTER COLUMN on databases that support it (skip SQLite)
    if bind.dialect.name != 'sqlite':
        # Make username NOT NULL
        op.alter_column(
            'user', 'username',
            existing_type=sa.VARCHAR(length=150),
            nullable=False
        )
        # Make password NOT NULL
        op.alter_column(
            'user', 'password',
            existing_type=sa.VARCHAR(length=150),
            nullable=False
        )
        # Remove the server_default for is_admin
        op.alter_column(
            'user', 'is_admin',
            existing_type=sa.BOOLEAN(),
            existing_server_default=sa.text('0'),
            server_default=None
        )
        # Remove the server_default for nfc_sent
        op.alter_column(
            'user', 'nfc_sent',
            existing_type=sa.BOOLEAN(),
            existing_server_default=sa.text('0'),
            server_default=None
        )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'nfc_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_column('user', 'stripe_subscription_id')
    op.drop_column('user', 'stripe_customer_id')
    op.drop_column('user', 'is_premium')
    # ### end Alembic commands ###
