"""Lägg till is_visible i Link

Revision ID: 61a3f1a2007d
Revises: 124df9fe0000
Create Date: 2025-05-03 21:21:04.678617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a3f1a2007d'
down_revision = '124df9fe0000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_column('is_visible')

    # ### end Alembic commands ###
