"""Clean up User model – remove duplicate columns

Revision ID: fa44886b8d34
Revises: 1d03963c3adb
Create Date: 2025-05-28 23:59:04.827426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa44886b8d34'
down_revision = '1d03963c3adb'
branch_labels = None
depends_on = None


def upgrade():
    # Förhindra fel om en tidigare batch-alter kraschade halvvägs
    op.execute('DROP TABLE IF EXISTS "__alembic_tmp_user";')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column(
            'username',
            existing_type=sa.VARCHAR(length=150),
            nullable=False
        )
        batch_op.alter_column(
            'password',
            existing_type=sa.VARCHAR(length=150),
            nullable=False
        )
    # ### end Alembic commands ###


def downgrade():
    # Om vi backar, sätt tillbaka nullable och ta bort temp-tabellen om den dykt upp igen
    op.execute('DROP TABLE IF EXISTS "__alembic_tmp_user";')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column(
            'password',
            existing_type=sa.VARCHAR(length=150),
            nullable=True
        )
        batch_op.alter_column(
            'username',
            existing_type=sa.VARCHAR(length=150),
            nullable=True
        )
    # ### end Alembic commands ###
